@startuml Открытие депозита
title Открытие депозита

actor "Клиент" as Клиент
actor "Кол-центр" as Кол_центр
participant "Система\nкол центра" as Система_кол_центра
actor "Сотрудники\nотделения" as Сотрудн_отделения
participant "АБС" as АБС
actor "Управление\nдепозитами" as Управ_депозитами
actor "Управление\nкредитами" as Управ_кредитами

participant "СМС-шлюз\nтелеком\nоператора" as СМС_шлюз
participant "E-mail" as Email
participant "Excel" as Excel

group Ежедневный расчёт ставки
    Управ_кредитами -> Excel : Расчёт ставок
    Управ_кредитами -> Email : Excel файл для расчёта ставки
    Email -> Управ_депозитами : Excel файл для расчёта ставки
end

group Предварительное обращение в колл центр для уточнения деталей депозита
    Клиент -> Кол_центр : Уточнение деталей депозита
    Кол_центр -> Система_кол_центра : Заводит обращение
    Система_кол_центра -> АБС : Передаёт данные
    АБС -> Управ_депозитами : Расчёт ставки
    Управ_депозитами -> АБС : Указание ставки
    АБС -> СМС_шлюз : Оповещение клиента
    СМС_шлюз -> Клиент : СМС с одобренной ставкой
end

group Обащение в отделение для открытия депозита
    Клиент -> Сотрудн_отделения : Открытие депозита
    Сотрудн_отделения -> АБС : Просмотр данных клиента

    alt Ставка предрассчитана т.к. был предварительный звонок в колл-центр
        АБС -> Сотрудн_отделения : Ставка
    else Клиент ны обращался в колл-центр
        Сотрудн_отделения -> Email : Запрос ставки
        Email -> Управ_депозитами : Запрос ставки
        Управ_депозитами -> АБС : Анализ данных и финансов клиента

        alt У клиента немного денег на счетах
            Управ_депозитами -> Excel : Просмотр текущей ставки
            Управ_депозитами -> Email : Отправка общей ставки
        else У клиента достаточно много денег на счетах
            Управ_депозитами -> Email : Запрос особой ставки
            Email -> Управ_кредитами : Запрос особой ставки
            Управ_кредитами -> АБС : Анализ кредитного риска для клиента
            Управ_кредитами -> Email : Данные кредитного риска клиента
            Email -> Управ_депозитами : Данные кредитного риска клиента
            Управ_депозитами -> Excel : Вычисление спец. ставки
            Управ_депозитами -> Email : Спец. ставка
        end

        Email -> Сотрудн_отделения : Ставка
    end

    Сотрудн_отделения -> Клиент : Ставка
    Клиент -> Сотрудн_отделения : Согласие на открытие депозита
    Сотрудн_отделения -> АБС : Открытие депозита
    Сотрудн_отделения -> Клиент : Документы на подпись
    Клиент -> Сотрудн_отделения : Подписанные документы
    Сотрудн_отделения -> АБС : Подписанные документы
end

@enduml
