@startuml Оформление кредита
title Оформление кредита

actor "Клиент" as Клиент
actor "Сотрудники\nотделения" as Сотрудн_отделения
participant "АБС" as АБС
participant "Кредитный\nконвейер" as Кредитный_конвейер
actor "Управление\nкредитами" as Управ_кредитами
participant "Кредитный\nскоринг" as Кредитный_скоринг
participant "API бюро\nкредитных\nисторий" as API_бюро_кредитных_историй

АБС -> Кредитный_скоринг : Данные о клиентах,\nИстория оплаты кредитов\n(раз в сутки)
Кредитный_конвейер -> Кредитный_скоринг : Номера платежей к кредитному договору\n(раз в сутки)

Клиент -> Сотрудн_отделения : Получение кредита
Сотрудн_отделения -> АБС : Заявка на получение кредита
АБС -> Кредитный_конвейер : Все заявки\n(раз в сутки)
Кредитный_конвейер -> Управ_кредитами : Изучение заявки
Управ_кредитами -> Кредитный_конвейер : Определение кредитного рейтинга клиента
Кредитный_конвейер -> Кредитный_скоринг : Определение кредитного рейтинга клиента
Кредитный_скоринг -> API_бюро_кредитных_историй : Запрос данных клиента
API_бюро_кредитных_историй -> Кредитный_скоринг : Данные клиента
Кредитный_скоринг -> Кредитный_конвейер : Кредитный рейтинг клиента
Кредитный_конвейер -> Управ_кредитами : Кредитный рейтинг клиента

alt Кредит одобнен
    Управ_кредитами -> Кредитный_конвейер : Одобрение кредита
    Кредитный_конвейер -> АБС : Одобренные кредиты\n(раз в сутки)
    АБС -> АБС : Зачисление кредитных средств на счет клиента
end

@enduml
